### ISSUE TITLE
tutorial needs an import for sc.compute_spectrogram function

### ISSUE THREAD

**Issue by avuan** [PeterMakus/SeisMIC#58]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

In the examples, if I run the tutorial "Plot a time-dependent spectrogram" 

from seismic.plot.plot_spectrum import plot_spct_series
from matplotlib import pyplot as plt

f, t, S = sc.compute_spectrogram('X9', 'IR1', 'HHE', starttime, endtime, 7200, freq_max=12.5)
fig = plt.figure(figsize=(9, 7))
plot_spct_series(S, f, t, log_scale=True)

the module sc is not found 

NameError                                 Traceback (most recent call last)
Cell In[1], line 4
      1 from seismic.plot.plot_spectrum import plot_spct_series
      2 from matplotlib import pyplot as plt
----> 4 f, t, S = sc.compute_spectrogram('X9', 'IR1', 'HHE', starttime, endtime, 7200, freq_max=12.5)
      5 fig = plt.figure(figsize=(9, 7))
      6 plot_spct_series(S, f, t, log_scale=True)

NameError: name 'sc' is not defined

### Code to Reproduce

```python
from seismic.plot.plot_spectrum import plot_spct_series
from matplotlib import pyplot as plt

f, t, S = sc.compute_spectrogram('X9', 'IR1', 'HHE', starttime, endtime, 7200, freq_max=12.5)
fig = plt.figure(figsize=(9, 7))
plot_spct_series(S, f, t, log_scale=True)
```

### Error Traceback

```Python traceback
NameError                                 Traceback (most recent call last)
Cell In[1], line 4
      1 from seismic.plot.plot_spectrum import plot_spct_series
      2 from matplotlib import pyplot as plt
----> 4 f, t, S = sc.compute_spectrogram('X9', 'IR1', 'HHE', starttime, endtime, 7200, freq_max=12.5)
      5 fig = plt.figure(figsize=(9, 7))
      6 plot_spct_series(S, f, t, log_scale=True)

NameError: name 'sc' is not defined
```

### SeisMIC Version?

last

### Operating System?

OS/X Ventura

### Python Version?

Python 3.11.5

### Installation Method?

conda

**Comment by avuan** [comment]
Thanks Peter. You are right and sorry for posting the issue

Il mer 6 set 2023, 16:34 Peter Makus ***@***.***> ha scritto:

**Comment by amell567** [comment]
Hello! Have you solved this problem? I just started to learn this software, and I also encountered this problem. Could you please tell me your method of adding jue? I would appreciate it very much！
