### ISSUE TITLE
problem about "network"

### ISSUE THREAD

**Issue by amell567** [PeterMakus/SeisMIC#64]
Hello, I collected some data by myself with a three-component seismograph, the original format of the data is DLD, the data can be converted into miniseed format using sololite, but there is no network information in the data, may I ask how to edit the network when I edit and sort the files? Can i define one myself?

**Comment by amell567** [comment]
![70d574647cf7e579715fb8f88973d1e](https://github.com/PeterMakus/SeisMIC/assets/161307980/69c73ec2-2f7b-44fb-9a05-e428fa374d97)

**Comment by PeterMakus** [comment]
Hi @amell567 ,
Thanks for getting in touch. I would recommend to use ObsPy to edit the metadata. You can just open the files using obspy.read and then edit the metadata fields that need to be adjusted in trace.stats.
Can surely be automated via a short script. Alternatively, you could use PyRocko to do the conversion and I think Pyrocko let's you update the metadata as well.
Best,
Peter

P.S.

I will close the issue for now because it is not really a SeisMIC related issue, but rather external. Feel free to answer to the thread though.

**Comment by amell567** [comment]
Thank you!My programming foundation is very weak, but seismic software is very convenient and helpful for my research direction. Sorry to bother you！
When I was Plotting a time-dependent spectrogram based on the SeisMIC Tutorial,he code execution showed an error,which meant that sc variable was referenced in the code, but the variable was not defined. I modified the code to define this variable, but an error was reported, my seismic has been correctly installed. Does this mean that I need to create a separate py file for the compute_spectrogram function?
![381b8cb824e7d23271f653867bdc1d5](https://github.com/PeterMakus/SeisMIC/assets/161307980/a6e2f8c3-8b8c-4e8a-aa38-8bef429627ae)
![f5dd0bf1154cdfb3b07e370a6dc4218](https://github.com/PeterMakus/SeisMIC/assets/161307980/8cea2c95-5dbf-4380-9051-944d1c45290d)

**Comment by amell567** [comment]
Hello, sorry to bother you! I had some problems when running monitore. py, but my params.yaml file seems to have no problems and was saved according to the tutorial. Please give me some suggestions, thank you very much！
<img width="775" alt="42fa1e48fae9a917ad47d482bc764b1" src="https://github.com/PeterMakus/SeisMIC/assets/161307980/9a6a6182-6cc1-406a-905c-d1328f21bc03">

**Comment by PeterMakus** [comment]
Hi, could you attach your params.yaml? This seems like the key mentioned in the error is missing in the parameter file (or is perhaps misspelled).

Best,
Peter

**Comment by amell567** [comment]
Hi，
Thank you very much for your help, I have solved this problem some time ago, just need to add 'return_sim_mat: True' to the "dv" code in the params.yaml file

**Comment by PeterMakus** [comment]
OK, that's what I was getting at. Perfect then!

**Comment by amell567** [comment]
Hello, I apologize for bothering you again! After running through the downloaded data as per your tutorial, it showed the correct results, then I started working on my own data, I intercepted the data from January 20 to January 29, 2024 and read the information contained in the data through the code, but when I plotted the spectrogram, it showed a problem, the problem stated that there was no data in this time period and I also tried to calculate the correlation and no h5 file is generated, can you please give me some suggestions?thank you very much!
![1714393130727](https://github.com/PeterMakus/SeisMIC/assets/161307980/c7f1a2a7-f278-49ca-9652-49670e0ca42c)

![1714392018678](https://github.com/PeterMakus/SeisMIC/assets/161307980/ad710d93-ccc6-48fc-a663-6791af8654f4)
![1714392038659](https://github.com/PeterMakus/SeisMIC/assets/161307980/ac6d0e61-e93a-4cbc-9d6b-894de9764096)
![1714392071879](https://github.com/PeterMakus/SeisMIC/assets/161307980/be044be4-8c72-468e-8265-092d48db3dd1)

**Comment by PeterMakus** [comment]
please refer to the obspy documentation here. The code snippet you sent does not contain any SeisMIC code.

**Comment by amell567** [comment]
Hello, I started to process my local miniseed data after running the data downloaded from the fdsn server successfully according to the tutorial. When dealing with correlation, I modified the file path and time in the correlate.py and params.yaml files, then processed it with mpi, but no h5 file was generated. Can you give me some advice？
![a66f85784d2b1efd48147373b161254](https://github.com/PeterMakus/SeisMIC/assets/161307980/e2e7a1e8-6683-4c7e-a64c-85bcc77ca92c)
![cdd438e9bc207d180fc25ef771fd9f2](https://github.com/PeterMakus/SeisMIC/assets/161307980/e7593215-d004-4542-92ee-16790eef7848)
![cc41a46ea5e29116b796e09b44c273e](https://github.com/PeterMakus/SeisMIC/assets/161307980/f15ff2e3-f57f-401a-9055-604dd245e521)
![b5517bc60cfcd39a9ad45f2c46165f6](https://github.com/PeterMakus/SeisMIC/assets/161307980/e3b1cf46-22f5-4ab0-a61a-be381f21594e)

**Comment by PeterMakus** [comment]
Hi,
judging from the screenshot, it looks like it did something though (the progress bar shows 9 steps).

Are you computing autocorrelations here? (i.e., setting to `autoComponents` in the params.yaml?).

Can you double-check that it did really not create a folder named _data3/corr_?

**Comment by amell567** [comment]
Hello, thank you very much for your help! Yes, it seems to be doing something, the progress bar shows 9 steps, but when I processed the data downloaded from the fdsn server according to your tutorial earlier, the progress bar showed 11 steps and the processing time was also 7 8 seconds, as shown in the first image. My local miniseed data is much larger than the one used in the tutorial, the processing steps should be longer and take a little longer, but only 9 steps are shown here, and after calculating the autocorrelation (I have setted to autoComponents in the params.yaml), a folder named data3/corr is created, but no h5 file is generated. So I don't know where the problem is, I feel that the calculation of autocorrelation is not doing a good job, can you give me some advice?
![image](https://github.com/PeterMakus/SeisMIC/assets/161307980/51c407d6-ac1b-4075-98bc-8686f20ba231)
![9f8de0415812446fc38afac0015218e](https://github.com/PeterMakus/SeisMIC/assets/161307980/228f8219-1bc4-42e7-b640-d934c012d591)
![846d868a51dcd271fcea72963d35b55](https://github.com/PeterMakus/SeisMIC/assets/161307980/fce84a63-b6e3-4bc3-a2f0-957ce8038a74)
![dc6f1bb7bcbdea9b75e8c4dc9e02553](https://github.com/PeterMakus/SeisMIC/assets/161307980/e1c425b7-10cf-4d6e-b3f0-b8ac1bbdbe30)
![41e082b7ae3b7aa689aed6052e18134](https://github.com/PeterMakus/SeisMIC/assets/161307980/30160aa3-8f43-4beb-bcda-a58cdd17e989)

**Comment by PeterMakus** [comment]
From the things you sent, it is very difficult to judge what is happening. Can you set the logging to ´DEBUG´? Also, do you have corresponding response files?

It seems like some unlogged error occurs for each of the files.

Also, it makes perfect sense that it shows 9 steps as you are processing 9 days of data (vs. 11 in the tutorial).

**Comment by PeterMakus** [comment]
Ok here is what I can tell from this:

SeisMIC manages to open the streams and preprocess them. But then it seems to think that none of them are valid to compute valid auto-correlations on.
I haven't heard of anything like that yet. But it does make me wonder which kind of data you are using. What does the channel code ´´DPE´´ stand for? What is it sampled it?
Can you open the mseed files using obspy.read and see if you can plot them normally?

**Comment by amell567** [comment]
Thank you for your patience, my miniseed data was extracted by sololite software, I have asked the staff of the seismograph company, the channel DPE may be related to the naming rules when the software exported the data, or it may be related to the software and database read, but it should not affect the processing of the data. The E in DPE is the component, and the channels of the three components are DPE,DPN,DPZ. In some data of others, I have also seen channels named BHE or ZNE, which may be because of the different naming rules. I used the code obspy.read to read the content of the day's data in my miniseed file, and drew the waveform diagram with another code, the result as shown in the figure, which should represent that the data is normal. Because the file size that can be uploaded here is limited, I have taken a small piece of data
[2024 1.20.zip](https://github.com/PeterMakus/SeisMIC/files/15411874/2024.1.20.zip)
, if it is convenient for you to download and understand my data. Once again to express my gratitude to you! 
![faffb7f158c726c5942d609f870bf82](https://github.com/PeterMakus/SeisMIC/assets/161307980/6d6162a4-0c67-4f7c-89a1-4c358bc1bdd9)
![12875baa19e79c61f1d343f5332b3b7](https://github.com/PeterMakus/SeisMIC/assets/161307980/4f702ff0-b989-4b9c-be84-144fe31d2512)
![13830da773234ee6408ec70dfb582d2](https://github.com/PeterMakus/SeisMIC/assets/161307980/1e1f71d8-0e74-46cd-807e-e1a6664d1aff)
![9127d21db83ef3150b1fdadce328ca3](https://github.com/PeterMakus/SeisMIC/assets/161307980/7aa16262-699d-46d3-86d6-34a98da20759)

**Comment by amel1567** [comment]
Thank you for your patience, my miniseed data was extracted by sololite software, I have asked the staff of the seismograph company, the channel DPE may be related to the naming rules when the software exported the data, or it may be related to the software and database read, but it should not affect the processing of the data. The E in DPE is the component, and the channels of the three components are DPE,DPN,DPZ. In some data of others, I have also seen channels named BHE or ZNE, which may be because of the different naming rules. I used the code obspy.read to read the content of the day's data in my miniseed file, and drew the waveform diagram with another code, the result as shown in the figure, which should represent that the data is normal. Because the file size that can be uploaded here is limited, I have taken a small piece of data, if it is convenient for you to download and understand my data. Once again to express my gratitude to you!
![faffb7f158c726c5942d609f870bf82](https://github.com/PeterMakus/SeisMIC/assets/170603277/a741a565-c800-4395-9159-abdab56a9a32)
![12875baa19e79c61f1d343f5332b3b7](https://github.com/PeterMakus/SeisMIC/assets/170603277/d6d2cba9-d4c0-45a0-b4a8-022a4b19deda)
![13830da773234ee6408ec70dfb582d2](https://github.com/PeterMakus/SeisMIC/assets/170603277/3f6831d6-f95f-46a7-8b66-8c945b6d2b5d)
![9127d21db83ef3150b1fdadce328ca3](https://github.com/PeterMakus/SeisMIC/assets/170603277/497c81ad-479f-4cb9-a9ad-5e13cd12b002)
[Uploading 2024 1.20.zip…]()

**Comment by amell567** [comment]
Thank you for your patience, my miniseed data was extracted by sololite software, I have asked the staff of the seismograph company, the channel DPE may be related to the naming rules when the software exported the data, or it may be related to the software and database read, but it should not affect the processing of the data. The E in DPE is the component, and the channels of the three components are DPE,DPN,DPZ. In some data of others, I have also seen channels named BHE or ZNE, which may be because of the different naming rules. I used the code obspy.read to read the content of the day's data in my miniseed file, and drew the waveform diagram with another code, the result as shown in the figure, which should represent that the data is normal.
![faffb7f158c726c5942d609f870bf82](https://github.com/PeterMakus/SeisMIC/assets/170603277/50ac1111-a672-467e-a9c2-6827bf81ec46)
![12875baa19e79c61f1d343f5332b3b7](https://github.com/PeterMakus/SeisMIC/assets/170603277/85812cfa-31c9-49cc-b2e4-0f67405a0a62)
![Uploading 13830da773234ee6408ec70dfb582d2.png…]()
![Uploading 9127d21db83ef3150b1fdadce328ca3.png…]()

**Comment by amell567** [comment]
Thank you for your patience, my miniseed data was extracted by sololite software, I have asked the staff of the seismograph company, the channel DPE may be related to the naming rules when the software exported the data, or it may be related to the software and database read, but it should not affect the processing of the data. The E in DPE is the component, and the channels of the three components are DPE,DPN,DPZ. In some data of others, I have also seen channels named BHE or ZNE, which may be because of the different naming rules. I used the code obspy.read to read the content of the day's data in my miniseed file, and drew the waveform diagram with another code, the result as shown in the figure, which should represent that the data is normal. 
![faffb7f158c726c5942d609f870bf82](https://github.com/PeterMakus/SeisMIC/assets/161307980/fff7e17d-f92e-4a69-b3e3-bed269eb2b05)
![12875baa19e79c61f1d343f5332b3b7](https://github.com/PeterMakus/SeisMIC/assets/161307980/bfc622cb-1c76-4cde-a7ad-2d8ed059a7aa)
![13830da773234ee6408ec70dfb582d2](https://github.com/PeterMakus/SeisMIC/assets/161307980/a2c12aab-47ab-46dd-9c7d-1c5c7631594b)
![9127d21db83ef3150b1fdadce328ca3](https://github.com/PeterMakus/SeisMIC/assets/161307980/fafd34b3-2fdd-4853-ab52-65bfc07f9582)

**Comment by PeterMakus** [comment]
Hm,
This all looks like it should work. Is there a chance that you could upload 2 days of your data to some cloud? Then I could see whether I can make it work on my machine.

One potential issue I see is that I never used SeisMIC on windows. In principle it should work, but all people I know have either been using Linux or MacOS.

**Comment by amell567** [comment]
I uploaded the data of 2023.11.20-11.21 to the onedrive cloud, is it convenient for you to download? In addition, the problem may be system related, but I think since I can follow the tutorial on windows to process the fdsn server data, I should be able to continue to process my local miniseed data, or maybe I know too little about Linux or MacOS. Thank you for taking so much time to help me, if the data on onedrive is not available, please let me know.The link of onedrive is here：https://1drv.ms/u/s!AhfXiwxM7b1Lcehqskamj5qXkrE?e=hIEP8g

**Comment by PeterMakus** [comment]
So here is what I think has happened:

You have named your files incorrectly. The last 3 digits in the filename correspond to the day of the year/julian day.
So for the data that you sent me the correct file names are:
´SS.14319..DPE.D.2023.324´ and ´SS.14319..DPE.D.2023.324´ because November 20th and 21st are the 324th and 325th day of the year 2023.
After renaming them accordingly, SeisMIC computed the correlations without any issue.

If they are named incorrectly, the data will be loaded but discarded immediately as it does not correspond to the expected times.

**Comment by PeterMakus** [comment]
Great! Happy to hear it works now!

**Comment by amel1567** [comment]
Hello, sorry to bother you again! I can get the result shown in the figure after calculating dv/v. Then I can directly extract the dv/v value corresponding to each time point through the npz file in the vel_change folder, so as to draw the dv/v image independently. However, if I want to redraw the correlation curve below in the graph, from which file should I extract the corresponding corr value? Since there are many corr folders after I calculated the correlation operation, which folder should I read the h5 file in?

**Comment by PeterMakus** [comment]
Hi,
The whole ``DV`` object is saved in the npz file. The different properties can be retrieved from the attributes, I will write a small sample code because I think it's easiest to understand:

```
from seismic.monitor.dv import read_dv

dv = read_dv('path/to/dv.npz')

# velocity change value is the -1* the stretch value, this value is decimal (for per cent multiply with 100)
vel_change = -1*dv.value
# corelation coefficient is stored here
cc = dv.corr
# the similarity matrix that the two values are retrieved from (i.e., the colormap in the background)
sim_mat = dv.sim_mat
```


This should do the trick,

Best,

Peter
