### ISSUE TITLE
Correlating data from various locations

### ISSUE THREAD

**Issue by PeterMakus** [PeterMakus/SeisMIC#65]
### Problem

Currently, ``CorrDB`` does not differ between data from various locations.

### Proposed solution

The probably easiest way to implement this into the current framework would be to create an additional subgroup in the hdf5 files, in the sense that the current hdf5 tree would be updated to **net0-net1/stat0-stat1/loc0-loc1/cha0-cha1**.

Important is to allow for backward compatibility with the old hdf5 structure. probably only possible by allowing for both file structures in the *params.yaml*.

**Comment by miic-sw** [comment]
Hi Peter,

ich bin wieder im Büro. Über dieses Thema müssen wir noch mal genauer sprechen.

Viele Grüße
Christoph




Christoph Sens-Schönfelder
Sektion 2.4, Seismologie
Building A46, Room 101
Tel.: +49 (0)331/6264-28705
Fax: +49 (0)331/6264-1277
Email: ***@***.***
___________________________________

Helmholtz-Zentrum Potsdam
Deutsches GeoForschungsZentrum GFZ
Stiftung des öff. Rechts Land Brandenburg
Telegrafenberg, 14473 Potsdam

**Comment by PeterMakus** [comment]
implemented in v0.6.0 (currently only available on `dev` branch). Documentation still needs to be updated accordingly.
