### ISSUE TITLE
A problem regarding the calculation of EGF in the high-frequency range

### ISSUE THREAD

**Issue by Yuuki-yuuki** [PeterMakus/SeisMIC#66]
### Problem

Hello, Peter:
    I am very interested in your work and appreciate the program you have released. But I have noticed that in certain frequency bands, especially in the high-frequency range, the calculated cross-correlation function shows some issues at Lag Time = -MAX, as shown in the figure below. 
    I am wondering if this is related to the use of the frequency domain method for calculating cross-correlation in the "correlate.py" file's "_pxcorr_matrix" function. Therefore, I am seeking your advice to understand whether this issue might affect the dvv results for high-frequency signals.

    
![1](https://github.com/PeterMakus/SeisMIC/assets/60815285/cc095670-ddc8-478f-b603-3531c22b71b1)
![2](https://github.com/PeterMakus/SeisMIC/assets/60815285/cb3b4139-e31e-42d7-b03b-a6f8f7af9500)

**Comment by PeterMakus** [comment]
Hi!
Oh that's interesting and certainly not physical.
Actually I am wondering whether this is a weird edge effect of the bandpass filter you applied.

On a different note: In which frequency band did you filter the seismic data before correlating? Because if you did not change the parameters in the tutorial then the data were filtered between 2 and 4 Hz, so I would not really expect any content between 6 and 8 Hz and that _might_ be the cause for this strange signal.

**Comment by PeterMakus** [comment]
PS The filters I am referring to are set in the _params.yaml_ file at this point:

`    corr_args : {'TDpreProcessing':[
                                  {'function':'seismic.correlate.preprocessing_td.taper',
                                    'args':{'type':'cosine_taper', 'p': 0.02}},
                                    {'function':'seismic.correlate.preprocessing_td.detrend',
                                    'args':{'type':'linear'}},
                                   {'function':'seismic.correlate.preprocessing_td.TDfilter',
                                   'args':{'type':'bandpass','freqmin':2,'freqmax':4}},
                                    #{'function':'seismic.correlate.preprocessing_td.mute',
                                    # 'args':{'taper_len':100.,
                                           # 'threshold':1000, absolute threshold
                                    #         'std_factor':3,
                                    #         'filter':{'type':'bandpass','freqmin':2,'freqmax':4},
                                    #         'extend_gaps':True}},
                                  #  {'function':'seismic.correlate.preprocessing_td.clip',
                                  #   'args':{'std_factor':2.5}},
                                   {'function':'seismic.correlate.preprocessing_td.signBitNormalization',
                                    'args': {}}
                                   ],
                  # Standard functions reside in seismic.correlate.preprocessing_fd
                 'FDpreProcessing':[
                                    # {'function':'seismic.correlate.preprocessing_fd.spectralWhitening',
                                    #  'args':{'joint_norm':False}},
                                    {'function':'seismic.correlate.preprocessing_fd.FDfilter',
                                     'args':{'flimit':[1.33, 2, 4, 6]}}
                                    #  {'function':seismic.correlate.preprocessing_fd.FDsignBitNormalization,
                                    # 'args':{}}
                                    ],`

**Comment by Yuuki-yuuki** [comment]
> Hi! Oh that's interesting and certainly not physical. Actually I am wondering whether this is a weird edge effect of the bandpass filter you applied.
> 
> On a different note: In which frequency band did you filter the seismic data before correlating? Because if you did not change the parameters in the tutorial then the data were filtered between 2 and 4 Hz, so I would not really expect any content between 6 and 8 Hz and that _might_ be the cause for this strange signal.

Thank you for replying, Peter. In fact, besides the example data in the tutorial, I used three datasets from different sites (including broadband seismometers and short-period seismometers), all with a sampling rate of 100Hz. During preprocessing, I modified the contents of 'params.yaml' to:

    sampling_rate : 50
    preProcessing : [
                    {'function':'seismic.correlate.preprocessing_stream.stream_filter',
                      'args':{'ftype':'bandpass',
                              'filter_option':{'freqmin':0.01, #0.01

    corr_args : {'TDpreProcessing':[
                                  {'function':'seismic.correlate.preprocessing_td.taper',
                                    'args':{'type':'cosine_taper', 'p': 0.02}},
                                    {'function':'seismic.correlate.preprocessing_td.detrend',
                                    'args':{'type':'linear'}},
                                   {'function':'seismic.correlate.preprocessing_td.TDfilter',
                                   'args':{'type':'bandpass','freqmin':1,'freqmax':24.99}},
                                               'freqmax':24.99}}}

However, in all three cases, the phenomena we mentioned earlier still exist. Fortunately, it almost does not affect the calculation results of DVV, but only affects the visualization effect of EGF.

**Comment by Yuuki-yuuki** [comment]
> > Hi! Oh that's interesting and certainly not physical. Actually I am wondering whether this is a weird edge effect of the bandpass filter you applied.
> > On a different note: In which frequency band did you filter the seismic data before correlating? Because if you did not change the parameters in the tutorial then the data were filtered between 2 and 4 Hz, so I would not really expect any content between 6 and 8 Hz and that _might_ be the cause for this strange signal.
> 
> Thank you for replying, Peter. In fact, besides the example data in the tutorial, I used three datasets from different sites (including broadband seismometers and short-period seismometers), all with a sampling rate of 100Hz. During preprocessing, I modified the contents of 'params.yaml' to:
> 
> ```
> sampling_rate : 50
> preProcessing : [
>                 {'function':'seismic.correlate.preprocessing_stream.stream_filter',
>                   'args':{'ftype':'bandpass',
>                           'filter_option':{'freqmin':0.01, #0.01
>                                            'freqmax':24.99}}}
> 
> corr_args : {'TDpreProcessing':[
>                               {'function':'seismic.correlate.preprocessing_td.taper',
>                                 'args':{'type':'cosine_taper', 'p': 0.02}},
>                                 {'function':'seismic.correlate.preprocessing_td.detrend',
>                                 'args':{'type':'linear'}},
>                                {'function':'seismic.correlate.preprocessing_td.TDfilter',
>                                'args':{'type':'bandpass','freqmin':1,'freqmax':24.99}},
>                                            'freqmax':24.99}}}
> ```
> 
> However, in all three cases, the phenomena we mentioned earlier still exist: ![YORYY N}7VB1X()%)ZW6X](https://private-user-images.githubusercontent.com/60815285/332630434-f85f447a-b8b2-4c11-8828-794d9ed069f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDM2ODcsIm5iZiI6MTcxNjM0MzM4NywicGF0aCI6Ii82MDgxNTI4NS8zMzI2MzA0MzQtZjg1ZjQ0N2EtYjhiMi00YzExLTg4MjgtNzk0ZDllZDA2OWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAyMDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmJkMDU4ZjdiNWE3YmVmMDI4MTk2YjMyMDllZDRlZjI2MjJmNzdmZTc1YzhiZjE5N2ZjMjk1YjU0NThjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V274HRfAAAAvVJR0JEwwiLl9Rf4ETnC5s5FSo0SGtx0)
> 
> Fortunately, it almost does not affect the calculation results of DVV, but only affects the visualization effect of EGF.

Wait, I noticed that I haven't modified the spectral whitening parameters. Could this be the issue? My FDpreProcessing parameters are still set to the default:

FDpreProcessing:
  # {'function':'seismic.correlate.preprocessing_fd.spectralWhitening',
  #  'args':{'joint_norm':False}},
  {'function':'seismic.correlate.preprocessing_fd.FDfilter',
   'args':{'flimit':[1.33, 2, 4, 8]}}
  # {'function':seismic.correlate.preprocessing_fd.FDsignBitNormalization,
  # 'args':{}}

**Comment by PeterMakus** [comment]
Hey!
So this is the issue here:
The seismic data is filtered 3 times. Once, the daily streams are filtered: with ´stream_filter´
Then, the matrix is filtered in the time domain. That is the option you set in ´TDPreProcessing´.
Lastly, it is filtered in the frequency domain (´FDpreProcessing´). And here you set a band that will not let any energy through. So basically this part
´´
{'function':'seismic.correlate.preprocessing_fd.FDfilter',
                                 'args':{'flimit':[1.33, 2, 4, 8]}}
´´
either needs to be commented or you change the filter parameters accordingly :). After doing that, I am pretty sure that the edge effect should disappear.


The reason why I filter three times is to avoid any numerical side effects from the preprocessing and the Fourier Transforms.

Just let me know if this works.

CHeers,
Peter

**Comment by Yuuki-yuuki** [comment]
Yes, you are absolutely right. After adjusting the flimit in 'FDpreProcessing', the edge effect completely disappeared. This indicates that the problem was not due to an error in the algorithm. Thank you for your patient response in helping me resolve this issue. Finally, I would like to ask if there are reasonable guidelines for setting the value of flimit. From what I understand, signal whitening requires two parameters, the lower limit and the upper limit, corresponding to f2 and f3 in FDfilter. Therefore, I'm not sure how the values of f1 and f4 will affect the results. Could you give me some advice?

![LG06UFLM7MK04%WLQ`D3T4L](https://github.com/PeterMakus/SeisMIC/assets/60815285/a5a1ab84-3e27-406f-a6b6-10e4712ba0d9)


By the way, I asked about this issue in ChatGPT, and the suggestions provided might be useful as a reference: try to choose f1 and f4 outside the frequency range of your signal of interest to ensure that the filter effectively preserves the main components of the signal. Specifically, f1 should be low enough to ensure that important low-frequency information is not filtered out; f4 should be high enough to ensure that important high-frequency information is not filtered out.

Does this mean that we can simply set f1 to a very low frequency and f4 to the Nyquist frequency?

**Comment by Yuuki-yuuki** [comment]
Yes, you are absolutely right. After adjusting the flimit in 'FDpreProcessing', the edge effect completely disappeared. This indicates that the problem was not due to an error in the algorithm. Thank you for your patient response in helping me resolve this issue. Finally, I would like to ask if there are reasonable guidelines for setting the value of flimit. From what I understand, spectral whitening requires two parameters, the lower limit and the upper limit, corresponding to f2 and f3 in FDfilter. Therefore, I'm not sure how the values of f1 and f4 will affect the results. Could you give me some advice?

![LG06UFLM7MK04%WLQ`D3T4L](https://github.com/PeterMakus/SeisMIC/assets/60815285/a5a1ab84-3e27-406f-a6b6-10e4712ba0d9)


By the way, I asked about this issue in ChatGPT, and the suggestions provided might be useful as a reference: try to choose f1 and f4 outside the frequency range of your signal of interest to ensure that the filter effectively preserves the main components of the signal. Specifically, f1 should be low enough to ensure that important low-frequency information is not filtered out; f4 should be high enough to ensure that important high-frequency information is not filtered out.

Does this mean that we can simply set f1 to a very low frequency and f4 to the Nyquist frequency?
