### ISSUE TITLE
Possible issue with computing velocity changes with dev versiom

### ISSUE THREAD

**Issue by imme-w** [PeterMakus/SeisMIC#72]
Hi Peter! I have succesfully installed the `dev` branch of seisMIC and used it to compute cross-correlations between different locations codes and it works! (see below) Thanks a lot for adding this feature :).
![image](https://github.com/PeterMakus/SeisMIC/assets/165271068/c927af4d-c8e1-40c3-86d9-4c4ffaedbce8)
I run into problems with computing the velocity changes with `monitor.py`. The issue is as follows, if I have my network parameter in params.yaml like this: 
```
net:
    # list of stations used in the project
    # type: list of strings or string, wildcards allowed
    network : ['MT', 'MT', 'MT']
    station : ['GAL', 'RUI', 'THE']
    component : 'Z'
```
`monitor.py` does not find the correlation files, as the output says this:
```
2024-07-09 13:46:36,845 - INFO - Found correlation data for the following station and network combinations []

0it [00:00, ?it/s]
0it [00:00, ?it/s]

```
I have discoved that changing the network parameters like this solves the issue:
```
net:
    # list of stations used in the project
    # type: list of strings or string, wildcards allowed
    network : 'MT'
    station : ['GAL', 'RUI', 'THE']
    component : 'Z'
```
because then the output of `monitor.py` (see below) gives the right combinations and velocity changes appear in the right directory.
```
2024-07-09 13:49:47,411 - INFO - Found correlation data for the following station and network combinations ['MT-MT.GAL-RUI', 'MT-MT.GAL-RUI', 'MT-MT.GAL-RUI', 'MT-MT.GAL-RUI', 'MT-MT.GAL-RUI', 'MT-MT.GAL-RUI', 'MT-MT.GAL-THE', 'MT-MT.GAL-THE', 'MT-MT.GAL-THE', 'MT-MT.GAL-THE', 'MT-MT.GAL-THE', 'MT-MT.GAL-THE', 'MT-MT.RUI-THE', 'MT-MT.RUI-THE', 'MT-MT.RUI-THE', 'MT-MT.RUI-THE']
```
But at some point I will be dealing with different network codes so the network parameter will have to be a list. I also discoverd if I have the net parameter as below, so a list with two different networks: 
```
#### parameters that are network specific
net:
    # list of stations used in the project
    # type: list of strings or string, wildcards allowed
    network : ['MT', 'MT', 'MT', 'FR']
    station : ['GAL', 'RUI', 'THE', 'OSG1']
    component : 'Z'

```
then the output of `monitor.py` looks like shown below, it appears to only compute cross-correlations between station combinations with a different network code.
```
2024-07-09 13:33:54,990 - INFO - Found correlation data for the following station and network combinations ['FR-MT.OGS1-GAL', 'FR-MT.OGS1-GAL', 'FR-MT.OGS1-GAL', 'FR-MT.OGS1-RUI', 'FR-MT.OGS1-RUI', 'FR-MT.OGS1-THE', 'FR-MT.OGS1-THE']
```

So my question is, am I doing something wrong? Thank you for thinking with me!

**Comment by PeterMakus** [comment]
Hi Imme, thanks for reporting the issue. I am looking into it!

**Comment by PeterMakus** [comment]
Was able to reproduce the bug and will take care of it :)
I think this should be an easy fix, I will come back to you asap

**Comment by PeterMakus** [comment]
Hi Imme,
Could you update your SeisMIC version to the one I released to the `dev` branch a minute ago?

Pretty sure that I fixed the issue.

A small side note: If you want to correlate from all available network codes, you could use a wildcard ('*') in the network parameters.

Any ways, let me know if this fixed your problem!

**Comment by imme-w** [comment]
Hi Peter! Thank you very much, I updated my SeisMIC version and indeed it works now! Also thanks for the tip about the wildcard, I had not thought about that yet.
