### ISSUE TITLE
 Load local data to correlate

### ISSUE THREAD

**Issue by mcardenass** [PeterMakus/SeisMIC#76]
### Problem

The documentation only includes an example of how to correlate the data if a client is used. The program correlate.py in the example folder has the commands to make it so.

### Suggested improvement

It would be useful to include an example or indicate what to modify in order to correlate data stored locally (on the computer), of course, as long as they are organized as shown in the example folder. Thank you for providing an example of that.

**Comment by PeterMakus** [comment]
Hi,

Thank you for pointing this out.

Have you come across the following: [Feed in waveform data in a different way](https://petermakus.github.io/SeisMIC/modules/trace_data/waveform.html#feed-in-data-in-a-different-way)

I will admit that it is not necessarily particularly detailed. However, the actual procedure is not very difficult. The easiest way of saving your own mseed data in a directory hierarchy that follows the outlined structure would be using jackseis (part of the pyrocko project).

**Comment by mcardenass** [comment]
Thanks Peter, I converted my data from SAC format to MSEED format using the sac2mseed program from SAC, and I have already placed my data in the recommended format in the folder.

data/mseed/{year}/{network}/{station}/HHE.D

These appear like this:
MA.MCCP..HHE.D.2024.085
..
..
MA.MCCP..HHE.D.2024.114

The file correlate.py assigns to the variables
root='data'
sc = Store_Client(None, root)

Is this correct? Well, in this case, we don't have the file {network}.{station}.xml in the inventory folder.

When running the program: !python correlate.py, I notice that the correlation file cannot be created in the corr folder. The result is:

/Users/mcardenass/anaconda3/envs/seismic/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
Correlator initiated
2024-10-13 09:29:11,801 - WARNING - No existing data found.
Automatically setting preprocess_subdiv to False to optimise performance.
100%|███████████████████████████████████████████| 29/29 [00:00<00:00, 84.94it/s]
Correlation finished after 0.3515348434448242 seconds

That is to say, it seems that it can't find the data.  Thank you for indicating that I need to modify.

Martin

**Comment by PeterMakus** [comment]
Hi Martin,
Yes, that seems like no suitable data can be found. Your data directory seems to be set up correctly though.

Could you send me the first section of your params.yaml file? (up to including the co section).

Also, you could re-run correlate with logging level set to ``DEBUG``(to be set in the params.yaml file) and see whether we get another helpful information.

**Comment by mcardenass** [comment]
Peter, 
The first section of params.yaml is:
#### Project wide parameters
# lowest level project directory
proj_dir : 'data'
# Save the component combinations in separate hdf5 files
# This is faster for multi-core if True
# Set to False for compatibility with SeisMIC version < 0.5.0
save_comps_separately: True
# directory for logging information
log_subdir : 'log'
# levels:
# 'DEBUG', 'INFO', 'WARNING', 'ERROR', or 'CRITICAL'
log_level: 'DEBUG'
# folder for figures
fig_subdir : 'figures'

#### parameters that are network specific
net:
    # list of stations used in the project
    # type: list of strings or string, wildcards allowed
    network : 'MA'
    station : 'MCCP'
    component : 'E'

After set  log_level: 'DEBUG' , I can see the correlation is done:

2024-10-13 13:00:20,822 - DEBUG - Calculating combinations...
2024-10-13 13:00:20,822 - INFO - No new data for times 2024-04-22T23:00:01.000000Z-2024-04-23T00:00:01.000000Z
100%|███████████████████████████████████████████| 29/29 [00:00<00:00, 76.59it/s]
Correlation finished after 0.388308048248291 seconds

But the correlation file (data/corr/MA-MA.MCCP-MCCP.HHE-HHE.h5) is not saved and it doesn't appear in the folder data/corr/

Also, I remeber that original sac file has the header KCMPNM as E.  I need to change it before convert to mseed?

**Comment by mcardenass** [comment]
Hi Peter,

I found the problem. When converting sac traces to mseed, it is necessary for the KCMPNM header to be HHE. With that, it's now possible to continue with the tutorial!!

One last question, how do I define **sc** in such a way that it can read the data stored locally and plot the spectrogram of the data?

sc = Store_Client(c,root,read_only=False) 
f, t, S = sc.compute_spectrogram('MC', 'MCCP', 'E', starttime, endtime, 7200, freq_max=4.0)


Thank you in advance

**Comment by PeterMakus** [comment]
Hi Martin,
Great to hear that you solved this problem!

Yes, you should be able to compute the spectrogram but since you do not have an inventory file /no response information, you will have to set ``remove_response=False``.
Also, I would set the Store_client to read_only. Otherwise, it will try downloading missing data from an the FDSN provider c.

Hence:

`
sc = Store_Client(c,root,read_only=True)
f, t, S = sc.compute_spectrogram('MC', 'MCCP', 'E', starttime, endtime, 7200, freq_max=4.0, remove_response=False)
`

Note that it is fastest to set `freq_max` so that 2*freq_max is a fraction of the sampling_rate, so the algorithm can decimate the data instead of having to interpolate.

**Comment by mcardenass** [comment]
Thanks, Peter, the tutorial has been adapted to my data. We stay in touch.

**Comment by mcardenass** [comment]
Thank you for all your work and for making your codes accessible.
